# Generated by Django 3.2.25 on 2024-11-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=10)),
                ('isOccupied', models.BooleanField()),
                ('bloq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloq.bloq')),
            ],
        ),
    ]
