# Generated by Django 3.2.25 on 2024-11-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='bloq',
            new_name='bloqId',
        ),
    ]
