# Generated by Django 3.2.25 on 2024-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_rename_bloq_locker_bloqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
    ]
