# Generated by Django 3.2.25 on 2024-11-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='locker',
            new_name='lockerId',
        ),
    ]
